server:
  port: 10002

spring:
  application:
    name: grpc-server
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: localhost:8848

grpc:
  server:
    port: 10012

instanceId: 2